### ISSUE TITLE
View all sessions and write enquiry message for new registrations in different consulting types

### ISSUE THREAD

**Issue by mobo4b** [Onlineberatung/onlineBeratung-frontend#14]
**Describe the solution you'd like**
As an asker I want to register to different consulting types with only one account to get advice for different problems.
In my profile I want to have an overview over all consulting types I already registered in and be able to register to other consulting types.
In my session list (my messages) I want to be able to write an enquiry message for any new registrations and see all (new) sessions.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context

**Comment by koepferd** [comment]
Feature is implemented in master.
