### ISSUE TITLE
Add formatting options for the input field

### ISSUE THREAD

**Issue by iam-robin** [Onlineberatung/onlineBeratung-frontend#7]
**Is your feature request related to a problem? Please describe.**
The user can only enter plain text in the input field and has no possibility to structure and format his message.

**Describe the solution you'd like**
Functions are provided to format and structure the messages within the input field. This includes text editing functions such as bold, italics and bullet points as well as color marking of links.

**Comment by koepferd** [comment]
Feature is implemented in master.
